/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WypiszRouteImport } from './routes/wypisz'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PrywatnoscRouteImport } from './routes/prywatnosc'
import { Route as IndexRouteImport } from './routes/index'

const WypiszRoute = WypiszRouteImport.update({
  id: '/wypisz',
  path: '/wypisz',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrywatnoscRoute = PrywatnoscRouteImport.update({
  id: '/prywatnosc',
  path: '/prywatnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/wypisz': typeof WypiszRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/wypisz': typeof WypiszRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/wypisz': typeof WypiszRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prywatnosc' | '/regulamin' | '/wypisz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prywatnosc' | '/regulamin' | '/wypisz'
  id: '__root__' | '/' | '/prywatnosc' | '/regulamin' | '/wypisz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrywatnoscRoute: typeof PrywatnoscRoute
  RegulaminRoute: typeof RegulaminRoute
  WypiszRoute: typeof WypiszRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wypisz': {
      id: '/wypisz'
      path: '/wypisz'
      fullPath: '/wypisz'
      preLoaderRoute: typeof WypiszRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prywatnosc': {
      id: '/prywatnosc'
      path: '/prywatnosc'
      fullPath: '/prywatnosc'
      preLoaderRoute: typeof PrywatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrywatnoscRoute: PrywatnoscRoute,
  RegulaminRoute: RegulaminRoute,
  WypiszRoute: WypiszRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
